version: '3'
services:
  atg:
    image: hallatech/oc-core:11.3
    command: tail -f /dev/null
    volumes:
    - /tmp/drivers:/drivers
    - ./buildtools/sql:/atg/sql
    depends_on:
    - db

  db:
    image: oracle/database:12.2.0.1-se2
    ports:
    - 1521:1521
    volumes:
    - atgdb_vol:/opt/oracle/oradata
    - ./buildtools/sql:/atg/sql
    environment:
    - ORACLE_PWD=Admin123

volumes:
  atgdb_vol:
    external: true